name: grow_assess
description: 儿童发育行为评估Flutter应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.1.1
  
  # 路由管理
  get: ^4.6.6
  
  # 数据库
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # 日期时间处理
  intl: ^0.18.1
  
  # 图片处理
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # 图表
  fl_chart: ^0.65.0
  
  # 文件处理
  path_provider: ^2.1.1
  
  # 工具库
  uuid: ^4.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/
    - data/ 